- hosts: all
  become: yes
#  roles:
#    - gantsign.java
#    - gantsign.maven 
#    - geerlingguy.nodejs
#    - geerlingguy.mysql

  vars:
    java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'
    mysql_enabled_on_startup: yes
    mysql_packages:
    - mariadb-client
    - mariadb-server
    - python-mysqldb

  tasks:
    - name: update installed software
      apt:
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
        state: latest

    - name: install git
      apt:
        name: git
        state: latest

    - name: download acme.sh
      git:
        repo: 'https://github.com/Neilpang/acme.sh.git'
        clone: yes
        dest: /etc/acme.sh

    - name: create new dhparams
      command: openssl dhparam -out /etc/nginx/dhparams.pem 4096
      args:
        creates: /etc/nginx/dhparams.pem
        
    - name: Copy database initialization file
      copy:
        src: /root/ansible/dbinit.sql
        dest: /tmp/dbinit.sql
        
    - name: Import database initialization
      mysql_db:
        state: import
        name: all
        target: /tmp/dbinit.sql
