---
spring:
  profiles: default
server.context-path: /safe-rides-api
server.port: 8080
management.security.enabled: false
spring.jpa.show-sql: true
spring.h2.console.enabled: true
jwt:
  header: Authorization
  secret: secretKeyGoesHere
  expiration: 43200

---
spring:
  profiles: dev
server:
  context-path: /api
  port: 8081