jwt:
  header: Authorization
  secret: secretKeyGoesHere
  expiration: 43200
api-keys:
  geocoding: AIzaSyBsvQDgFRvtFyInVOv0U_HrDaNsrnCuLhc
cas:
  server-url-prefix: https://sacauth.csus.edu/csus.cas/
---
spring:
  profiles: default
server.context-path: /safe-rides-api
server.port: 8080
spring.jpa.show-sql: true
spring.h2.console.enabled: true
ac.alloworigin: http://localhost:9000
---
spring:
  profiles: dev
server:
  context-path: /api
  port: 8081
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop
spring.datasource:
  url: jdbc:mysql://codeteam6.io:3306/SafeRides
  username: safeRidesAdmin
  password: D<)y$FuTecG].Q_YY._~'u?;
spring.h2.console.enabled: false
ac.alloworigin: https://codeteam6.io
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379